apiVersion: v1
kind: Pod
metadata:
  name: employees-pod
  namespace: employees
  labels:
    app: employees-pod
spec:
  containers:
    - name: employees
      image: employees:v2
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: DBHOST
          value: mysql-service.mysql
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: root
        - name: DBPWD
          value: password
        - name: DBNAME
          value: employees
