apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-deployment
  namespace: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
        - name: employees
          image: employees:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: mysql-service.mysql
            - name: DBPORT
              value: "3306"
            - name: DBUSER
              value: root
            - name: DBPWD
              value: password
            - name: DBNAME
              value: employees
