apiVersion: v1
kind: Pod
metadata:
  name: employees-pod
  namespace: employees
  labels:
    app: employees
spec:
  containers:
  - name: employees
    image: 691754694477.dkr.ecr.us-east-1.amazonaws.com/clo835-app:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

    env:
    - name: DBHOST
      value: mysql-service.mysql.svc.cluster.local
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: root
    - name: DBPWD
      value: password
    - name: DATABASE
      value: employees
